framework:
  validation:
    email_validation_mode: html5

    # Enables validator auto-mapping support.
    # For instance, basic validation constraints will be inferred from Doctrine's metadata.
    #auto_mapping:
#    App\Entity\Project:
#      properties:
#        img:
#          - Image:
#              minWidth: 200
#              maxWidth: 400
#              minHeight: 200
#              maxHeight: 400

when@test:
  framework:
    validation:
      not_compromised_password: false
